#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
version: '2'

services:

  ca.insurance.example.com:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-insurance
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.insurance.example.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/395db32256764341f6001c6d4abe7b857c55c9f0b294c6c5214be3cfa0d0a8af_sk
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.insurance.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/395db32256764341f6001c6d4abe7b857c55c9f0b294c6c5214be3cfa0d0a8af_sk
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./channel/crypto-config/peerOrganizations/insurance.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca-insurance

  ca.hospital.example.com:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-hospital
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.hospital.example.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/87bcbfca1475065ac03b81a83175be8cb66d62f606d957f51a19f7eabb3494c4_sk
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.hospital.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/87bcbfca1475065ac03b81a83175be8cb66d62f606d957f51a19f7eabb3494c4_sk
    ports:
      - "8054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./channel/crypto-config/peerOrganizations/hospital.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca-hospital

  ca.patient.example.com:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-patient
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.patient.example.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/ef7eaee27a4f8c902f630b3ed741298092aefb7f95d7bdd127d3a9922501e383_sk
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.patient.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/ef7eaee27a4f8c902f630b3ed741298092aefb7f95d7bdd127d3a9922501e383_sk
    ports:
      - "9054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./channel/crypto-config/peerOrganizations/patient.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca-patient

  orderer.example.com:
    container_name: orderer.example.com
    image: hyperledger/fabric-orderer
    environment:
      - FABRIC_LOGGING_SPEC=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/crypto/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/etc/hyperledger/crypto/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/etc/hyperledger/crypto/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/etc/hyperledger/crypto/orderer/tls/ca.crt, /etc/hyperledger/crypto/peerInsurance/tls/ca.crt, /etc/hyperledger/crypto/peerHospital/tls/ca.crt, /etc/hyperledger/crypto/peerPatient/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderers
    command: orderer
    ports:
      - 7050:7050
    volumes:
        - ./channel:/etc/hyperledger/configtx
        - ./channel/crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/:/etc/hyperledger/crypto/orderer
        - ./channel/crypto-config/peerOrganizations/insurance.example.com/peers/peer0.insurance.example.com/:/etc/hyperledger/crypto/peerInsurance
        - ./channel/crypto-config/peerOrganizations/hospital.example.com/peers/peer0.hospital.example.com/:/etc/hyperledger/crypto/peerHospital
        - ./channel/crypto-config/peerOrganizations/patient.example.com/peers/peer0.patient.example.com/:/etc/hyperledger/crypto/peerPatient

  peer0.insurance.example.com:
    container_name: peer0.insurance.example.com
    extends:
      file:   base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.insurance.example.com
      - CORE_PEER_LOCALMSPID=InsuranceMSP
      - CORE_PEER_ADDRESS=peer0.insurance.example.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.insurance.example.com:7051      
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.insurance.example.com:7051
    ports:
      - 7051:7051
      - 7053:7053
    volumes:
        - ./channel/crypto-config/peerOrganizations/insurance.example.com/peers/peer0.insurance.example.com/:/etc/hyperledger/crypto/peer
    depends_on:
      - orderer.example.com

  peer1.insurance.example.com:
    container_name: peer1.insurance.example.com
    extends:
      file:   base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.insurance.example.com
      - CORE_PEER_LOCALMSPID=InsuranceMSP
      - CORE_PEER_ADDRESS=peer1.insurance.example.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.insurance.example.com:7051      
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.insurance.example.com:7051
    ports:
      - 7056:7051
      - 7058:7053
    volumes:
        - ./channel/crypto-config/peerOrganizations/insurance.example.com/peers/peer1.insurance.example.com/:/etc/hyperledger/crypto/peer
    depends_on:
      - orderer.example.com

  peer0.hospital.example.com:
    container_name: peer0.hospital.example.com
    extends:
      file:   base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.hospital.example.com
      - CORE_PEER_LOCALMSPID=HospitalMSP
      - CORE_PEER_ADDRESS=peer0.hospital.example.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.hospital.example.com:7051      
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.hospital.example.com:7051
    ports:
      - 8051:7051
      - 8053:7053
    volumes:
        - ./channel/crypto-config/peerOrganizations/hospital.example.com/peers/peer0.hospital.example.com/:/etc/hyperledger/crypto/peer
    depends_on:
      - orderer.example.com

  peer1.hospital.example.com:
    container_name: peer1.hospital.example.com
    extends:
      file:   base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.hospital.example.com
      - CORE_PEER_LOCALMSPID=HospitalMSP
      - CORE_PEER_ADDRESS=peer1.hospital.example.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.hospital.example.com:7051      
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.hospital.example.com:7051
    ports:
      - 8056:7051
      - 8058:7053
    volumes:
        - ./channel/crypto-config/peerOrganizations/hospital.example.com/peers/peer1.hospital.example.com/:/etc/hyperledger/crypto/peer
    depends_on:
      - orderer.example.com

  
  peer0.patient.example.com:
    container_name: peer0.patient.example.com
    extends:
      file:   base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.patient.example.com
      - CORE_PEER_LOCALMSPID=PatientMSP
      - CORE_PEER_ADDRESS=peer0.patient.example.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.patient.example.com:7051      
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.patient.example.com:7051
    ports:
      - 9051:7051
      - 9053:7053
    volumes:
        - ./channel/crypto-config/peerOrganizations/patient.example.com/peers/peer0.patient.example.com/:/etc/hyperledger/crypto/peer
    depends_on:
      - orderer.example.com

  peer1.patient.example.com:
    container_name: peer1.patient.example.com
    extends:
      file:   base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.patient.example.com
      - CORE_PEER_LOCALMSPID=PatientMSP
      - CORE_PEER_ADDRESS=peer1.patient.example.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.patient.example.com:7051      
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.patient.example.com:7051
    ports:
      - 9056:7051
      - 9058:7053
    volumes:
        - ./channel/crypto-config/peerOrganizations/patient.example.com/peers/peer1.patient.example.com/:/etc/hyperledger/crypto/peer
    depends_on:
      - orderer.example.com